[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
numpy = "^1.22.2"
replit = "^3.2.4"
Flask = "^2.2.0"
urllib3 = "^1.26.12"
Flask-RESTful = "^0.3.10"
Flask-Cors = "^3.0.10"
Flask-Caching = "^2.0.2"
APScheduler = "^3.10.1"
pandas = "^2.0.2"
seaborn = "^0.12.2"
matplotlib = "^3.7.1"
plup-hello = "^0.4.2"
scripts = "^2.0"
tools = {version = "^0.1.9", python = ">=3.10,<3.11"}


[tool.poetry.dev-dependencies]
debugpy = "^1.6.2"
replit-python-lsp-server = {extras = ["yapf", "rope", "pyflakes"], version = "^1.5.9"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"